### ISSUE TITLE
Cant run the example project.

### ISSUE THREAD

**Issue by RamdhaSOi** [tradingticket/TradeItIosTicketSDK2#109]
Tried to run the given example app project, but not able. Facing multiple error regarding missing framework like **promiseKit, MBProgressHUD, SwiftyUserDefaults** . Can you guide me, what are the setup need to do?
Thanks

**Comment by imougy** [comment]
I had the same issue. You need to open the terminal and go to the folder of the SDK and then type "pop update". Then open the workspace, not the project.

**Comment by jsom** [comment]
Yes - you will need to use Cocoapods to run the ExampleApp provided.

**Comment by RamdhaSOi** [comment]
Thanks, pod update fixed my problem.
