### ISSUE TITLE
When changing the text size of the device, things are messed up

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#110]
If you change the text side under Settings app > Accessibility > Text Font, you will see this artifact in the layout. We need to have a consistent layout even if the text size changes by the user.
![image](https://cloud.githubusercontent.com/assets/3361440/22804624/b66aa71e-eece-11e6-910c-f1ea6a6db126.png)

**Comment by jsom** [comment]
Thanks @imougy - we are rewriting the whole portfolio view so this won't be fixed for this version. Did you see these issues on non-portfolio screens?
