### ISSUE TITLE
disclose icon is beyond ugly!

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#111]
![image](https://cloud.githubusercontent.com/assets/3361440/22804656/d9cc1bde-eece-11e6-8cfd-4d2ee3be3aaa.png)

**Comment by jsom** [comment]
@imougy I laughed but you're absolutely correct. We're doing some styling updates next week, so this should be fixed soon to just be the standard disclose icon.

**Comment by jsom** [comment]
This should be resolved in 1.1

**Comment by imougy** [comment]
Nice, tested.
