### ISSUE TITLE
Margins need some love 

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#112]
![image](https://cloud.githubusercontent.com/assets/3361440/22804720/2e6ecc86-eecf-11e6-82cc-0ae544b699b3.png)

**Comment by imougy** [comment]
Same for the iPad layout
![image](https://cloud.githubusercontent.com/assets/3361440/22855793/8a72c4b2-f03a-11e6-91d4-44e9488b786e.png)

**Comment by jsom** [comment]
This should be resolved in 1.1

**Comment by imougy** [comment]
Nice, tested.
