### ISSUE TITLE
What is the equivalent new API to the old one [[TTSDKUtils sharedUtils] isOnboarding]

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#137]
Thanks,

**Comment by jsom** [comment]
The new SDK manages the welcome flow and will pop it up when necessary so you shouldn't need `isOnboarding` anymore.

**Comment by imougy** [comment]
I need to know this state because when a user tries to sync, I need to display a guide, telling them they need to link to brokers first. Otherwise, I proceed with the sync operation.

**Comment by jsom** [comment]
Does that have any extra meaning beyond just checking if any existing brokers have been linked?

```
[TradeItSDK.linkedBrokerManager.linkedBrokers count];
```

**Comment by imougy** [comment]
That will work.
Thanks!
