### ISSUE TITLE
A big jerky jump when you tap on an account in the Trade view

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#140]
After launchTradingFromViewController and if you tap on an account to change the current account, you will see the accounts in a table view then there is a jump to accommodate for the header of the table. It seems something happened inside viewDidAppear() but it should be inside viewWillAppear. Please make the transition smooth.

![simulator screen shot mar 5 2017 12 40 11 am](https://cloud.githubusercontent.com/assets/3361440/23585815/a1c750c0-013c-11e7-80c8-18433dab0f04.png)

**Comment by bluk16** [comment]
In the new version 1.1, switching to the account view is no longer jumpy.
