### ISSUE TITLE
API needs to be objective C compatible

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#141]
For example, the API in TradeItOrder
>     public func preview(onSuccess: @escaping (TradeItPreviewTradeResult, @escaping TradeItPlaceOrderHandlers) -> Void,
>                            onFailure: @escaping (TradeItErrorResult) -> Void
> 
Give this error while writing ObjC code:-
<img width="1227" alt="screen shot 2017-03-05 at 12 46 06 pm" src="https://cloud.githubusercontent.com/assets/3361440/23591206/c7987486-01a1-11e7-8bd2-e27bf7c4904d.png">

Also, for this API 

>     [TradeItSDK configureWithApiKey:PUBLISHER_NAME environment:TradeItEmsProductionEnv];

Please make sure NOT to set a default value for the parameter, otherwise, I am getting this error:-
![image](https://cloud.githubusercontent.com/assets/3361440/23591228/036e48dc-01a2-11e7-966c-484d2bf85832.png)

**Comment by imougy** [comment]
I think this is a wider problem, please make all the APIs work with Objective-C without issues.
Another example:-
![image](https://cloud.githubusercontent.com/assets/3361440/23596694/cbaf8e34-01e1-11e7-871e-096663dfeac8.png)

Thanks,

**Comment by jsom** [comment]
I'm going to create an Obj-C ExampleApp this week which should address any of these quirks.

**Comment by jsom** [comment]
I have pushed a basic example app for Objective-C that covers the calls above. They were already compatible with Objective-C but you just need to add parameter names in the right place. See here:

https://github.com/tradingticket/TradeItIosTicketSDK2/blob/develop/ExampleAppObjC/ViewController.m

Make sure you import the Objective-C header as well to get access to the Environments:

```
#import <TradeItIosTicketSDK2/TradeItIosTicketSDK2.h>
```

I also pulled out a `typedef` for the `PlaceOrder` callback that should read cleaner.

**Comment by imougy** [comment]
My point was you add the parameter with your convention so others will just use xcode autofill and start working, without guessing what should I write there.

**Comment by imougy** [comment]
Cosmetic, not a big deal.
Fix if you have time or close.

**Comment by mitochondrion** [comment]
When you pass a block as an argument, you are defining the block so you will always have to name the parameters to your block. If you want XCode to add a placeholder when autocompleting block arguments, you'll need to file a Radar ticket with Apple: https://bugreport.apple.com.
