### ISSUE TITLE
TradeItPortfolioPosition architecture

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#142]
It doesn't look good to have two objects inside this position, one for forex and one for equity! Why not have one base portfolio position (TradeItPortfolioPosition) and then have forex (TradeItPortfolioFXPosition) and equity (TradeItPortfolioEquityPosition) derived from it.  The caller will then check the type if needed and it will be simpler code.

**Comment by mitochondrion** [comment]
This is an unfortunate side effect of the specific JSON serialization library that was used for the initial SDK code. It does not support polymorphic JSON fields.
