### ISSUE TITLE
When displaying launchAccountSelectionFromViewController buying power is N/A

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#145]
Sometimes it display something but other times it doesn't

![simulator screen shot mar 11 2017 4 05 17 pm](https://cloud.githubusercontent.com/assets/3361440/23827917/e4954168-0674-11e7-8a0a-1adee4a8deac.png)

**Comment by bluk16** [comment]
It should be resolved in version 1.1 

<img width="374" alt="sample" src="https://cloud.githubusercontent.com/assets/12431442/24379919/316d31a4-1317-11e7-827e-2b63c79e72e1.png">
