### ISSUE TITLE
In TradeItAccountOverview, missing margin cash

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#146]
Many brokers, like TD and Robinhood, have margin cash, it is an important field to give the overall view of the account total value.
I remember this field was added but I can't see it in the new SDK.
Thanks,

**Comment by bluk16** [comment]
The margin cash field is available in version 1.1

**Comment by imougy** [comment]
But what about the latest SDK, I didn't see it.
