### ISSUE TITLE
Updating the pod spec for SDK 1.1?

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#151]
I can't get the latest using pod update.
Thanks,

**Comment by bluk16** [comment]
Can you try ```pod update``` then ```pod install```?

**Comment by jsom** [comment]
You may need to run `pod repo update` first to pull the latest specs and ensure that you have `~> 1.1.0` in your `Podfile`.

**Comment by imougy** [comment]
I needed to update the podfile.
Awesome!
