### ISSUE TITLE
Title of TD broker is wrong

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#155]
Please make sure that it is TD, also check all the other brokers.
Low priority.

Thanks,
![screen shot 2017-03-29 at 11 20 55 pm](https://cloud.githubusercontent.com/assets/3361440/24490604/174097fe-14d8-11e7-8a40-d4a6a4589810.png)

**Comment by jsom** [comment]
@imougy we now store the broker display name in `1.1.30`. Once the user links/relinks it'll show the well formatted name.
