### ISSUE TITLE
Options formatting is wrong while syncing

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#168]
Options ticker shouldn't have any spaces in them, please remove the spaces so we can parse them properly.
This is ASAP please.

**Comment by TheAntonioReyes** [comment]
Hey Ilam, we follow the OCC standard https://en.wikipedia.org/wiki/Option_symbol which does includes spaces for some symbols

**Comment by imougy** [comment]
Hi Antonio, the spaces are not needed for the storing, look at Yahoo finance for example. Is removing the space will break anyone? Having the spaces breaks my app now.

**Comment by TheAntonioReyes** [comment]
Unfortunately yes, we have a couple partners who have worked closely on the mapping with us as they do use it. I'll see what we might be able to do for a quick solution for you though.

**Comment by imougy** [comment]
👍
