### ISSUE TITLE
Title of the Select account to sync is not visible...

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#184]
![simulator screen shot jun 15 2017 9 40 10 pm](https://user-images.githubusercontent.com/3361440/27212252-87626ec2-5213-11e7-9d0b-0d4c141811cf.png)

**Comment by imougy** [comment]
Any update on this issue?

**Comment by imougy** [comment]
Since I can't do pull request, can you please update the bug with the fix below.
Thanks,
[fix for label color.txt](https://github.com/tradingticket/TradeItIosTicketSDK2/files/1290836/fix.for.label.color.txt)

**Comment by jsom** [comment]
@imougy it looks like you modified the top bar yourself to give it a black background. That's not something that the current SDK theming system does. What code are you using to change that? I can't change the title to white because it will change it for all partners using the SDK.

**Comment by imougy** [comment]
I use the `[[UINavigationBar appearance] setBarTintColor:[UIColor blackColor]];`.  The weird thing is this is the ONLY dialog that has this issue from the SDK, the rest of the dialogs are displaying white text, here is example:-

![simulator screen shot sep 11 2017 9 58 38 am](https://user-images.githubusercontent.com/3361440/30286830-d42910b8-96d7-11e7-8036-a837b15f2800.png)

What do you suggest then to solve this issue?
I will change the theme to dark and let you know.

**Comment by imougy** [comment]
I tried the dark theme and here is what I see:-

![screen shot 2017-09-11 at 10 08 41 am](https://user-images.githubusercontent.com/3361440/30287310-6aaf292c-96d9-11e7-94e9-028b0b5d69ec.png)

Also note, in my app, I use those lines to control my app appearance:-

`    NSDictionary *textTitleOptions = [NSDictionary dictionaryWithObjectsAndKeys:[UIColor whiteColor], NSForegroundColorAttributeName, nil];
    [[UINavigationBar appearance] setTitleTextAttributes:textTitleOptions];
    [[UINavigationBar appearance] setBarTintColor:[UIColor blackColor]];
    [[UINavigationBar appearance] setBarStyle:UIBarStyleBlack];
`

**Comment by jsom** [comment]
OK - I will look at fixing this tomorrow. I have an idea what it might be. Should be in the next version.

**Comment by imougy** [comment]
Awesome! tested and worked fine.
Thanks,

**Comment by imougy** [comment]
Can you please make sure it makes it to the pod.
Thanks,

**Comment by jsom** [comment]
Yep, it'll be in the next release
