### ISSUE TITLE
Dummy broker name same for "Dummy and DummyMultiple" account

### ISSUE THREAD

**Issue by RamdhaSOi** [tradingticket/TradeItIosTicketSDK2#204]
Broker name for the Dummy and DummyMultiple account is same as "Dummy". Will be helpful, If the name is different. So, that we can use it as different broker account.

**Comment by jsom** [comment]
Hey @RamdhaSOi - what would you expect to see in this case?

**Comment by RamdhaSOi** [comment]
Any different broker name. E.g Dummy - dummy, DummyMultiple- dummyMultiple

**Comment by jsom** [comment]
@RamdhaSOi both `dummy` and `dummyMultiple` are both logins for the `Dummy` broker. They are not 2 separate brokers. A user could indeed connect 2 logins for the same broker but that information would not be held in the broker name. You would need to look at the underlying account objects.

**Comment by RamdhaSOi** [comment]
Ok, got it. But, expecting it as two different brokers. So, it will be useful to work for user, who have two broker accounts.

**Comment by jsom** [comment]
Closing issue as it is working as expected for now and is a rare edge case.
