### ISSUE TITLE
Bundle contains large size images

### ISSUE THREAD

**Issue by kafejo** [tradingticket/TradeItIosTicketSDK2#220]
By inspecting an IPA of our product the TradItIosSDK has the largest size from all frameworks we link you our project. I found that the bundle contains few PNG that has over 100KB (one of them even 0.5MB). I believe it is not necessary to have them that large.

![tradeking_logo](https://user-images.githubusercontent.com/4762172/29248881-2300045e-801b-11e7-9448-fd36b4444506.png)

<img width="403" alt="screen shot 2017-08-13 at 11 33 24" src="https://user-images.githubusercontent.com/4762172/29248887-42cd0282-801b-11e7-8558-9fe46ab77284.png">

**Comment by jsom** [comment]
Thanks - I have cleaned this up. They were leftover from the old broker center. You can see the commit here: https://github.com/tradingticket/TradeItIosTicketSDK2/commit/7a90fb88be9915cf8f44976eb0d6d9d5f624c604
