### ISSUE TITLE
Xcode 9 Archive Error

### ISSUE THREAD

**Issue by henrypratt** [tradingticket/TradeItIosTicketSDK2#271]
Builds and runs with Xcode 9, but when attempting to archive, I get the error “command failed due to signal: abort trap: 6”.

**Comment by jsom** [comment]
Hi @henrypratt -- I'm using Xcode 9 and am able to archive. Any more debugging information? How did you determine it was the SDK that was the cause of the problem? Is this in an existing application or a fresh project?

**Comment by henrypratt** [comment]
This is an existing application. I am using SDK v1.1.31

When trying to compile, everything in the TradeIt SDK compiles properly, except for 'TradeItRequestFactory.swift'.

This is the error data:
`Global is external, but doesn't have external or weak linkage!
i8** @_T0SC22TradeitEmsEnvironmentsVs9Equatable20TradeItIosTicketSDK2WP
<unknown>:0: error: fatal error encountered during compilation; please file a bug report with your project and the crash log
<unknown>:0: note: Broken module found, compilation aborted!
0  swift                    0x000000010e4d5dba PrintStackTraceSignalHandler(void*) + 42
1  swift                    0x000000010e4d51f6 SignalHandler(int) + 662
2  libsystem_platform.dylib 0x00007fffc32b5b3a _sigtramp + 26
3  libsystem_platform.dylib 0x0000000000000004 _sigtramp + 1020568804
4  libsystem_c.dylib        0x00007fffc313a420 abort + 129
5  swift                    0x000000010ae44fe7 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*)::$_0::__invoke(void*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) + 551
6  swift                    0x000000010e4933fb llvm::report_fatal_error(llvm::Twine const&, bool) + 571
7  swift                    0x000000010e4931ba llvm::report_fatal_error(char const*, bool) + 42
8  swift                    0x000000010e469654 (anonymous namespace)::VerifierLegacyPass::doFinalization(llvm::Module&) + 260
9  swift                    0x000000010e4162c3 llvm::FPPassManager::doFinalization(llvm::Module&) + 83
10 swift                    0x000000010e41b4f7 llvm::legacy::FunctionPassManagerImpl::doFinalization(llvm::Module&) + 71
11 swift                    0x000000010afbe795 swift::performLLVM(swift::IRGenOptions&, swift::DiagnosticEngine*, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, swift::version::Version const&, llvm::StringRef, swift::UnifiedStatsReporter*) + 5045
12 swift                    0x000000010ae49c18 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 19496
13 swift                    0x000000010ae43784 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7716
14 swift                    0x000000010adf86a8 main + 12248
15 libdyld.dylib            0x00007fffc30a6235 start + 1
16 libdyld.dylib            0x0000000000000056 start + 1022729762
 `

**Comment by jsom** [comment]
Thanks - that's helpful. I'm unable to replicate it locally. Are you using Carthage or Cocoapods?

**Comment by henrypratt** [comment]
Cocoapods

**Comment by henrypratt** [comment]
Fixed by updating cocoapods
