### ISSUE TITLE
Objective-C compatibility...

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#56]
The public APIs needs to be Obj-C ready, for example:-
open func launchTrading(fromViewController viewController: UIViewController, withOrder order: TradeItOrder = TradeItOrder())

**Comment by adamkaplan** [comment]
+1 to this. Most of it is fixed with a simple `@objc` annotation.

**Comment by jsom** [comment]
This should be resolved now.
