### ISSUE TITLE
Need API to select an account given a viewcontroller

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDK2#57]

**Comment by jsom** [comment]
@imougy can you add some detail to this? Do you just want to be able to launch account selection and then return the account to your app?

**Comment by imougy** [comment]
Yes, I also need to customize the title of the controller to anything I want. The current version is hard coded to "Select account to trade...", I want "Select account to sync...". I will use it to link an internal portfolio with a broker account. You can see Stocks Live Free (blue icon) for an example.

**Comment by jsom** [comment]
Hello @imougy this feature is live as of this commit: https://github.com/tradingticket/TradeItIosTicketSDK2/commit/6e9a9b99a751557c7711afc1ec7dba1b715a9b1d

Let me know if this works and close the issue if it's working correctly.
