### ISSUE TITLE
Missing nullability specifiers all over the place

### ISSUE THREAD

**Issue by adamkaplan** [tradingticket/TradeItIosTicketSDK2#66]
These generate compiler warnings for the framework, and since the public headers are included client apps, the warnings cascade to the clients. It’s very very annoying if your team (responsibly) uses “Treat warnings as errors”.

**Comment by jsom** [comment]
We're working with some legacy code and trying to clean up as we go. I took care of some of them last week: https://github.com/tradingticket/TradeItIosTicketSDK2/commit/15f685f5263e6acc940fcf46967fffe6cd0f1ef8

Did you get those changes? I'm only seeing 3 deprecation warnings and no nullability warnings in my builds now. I can take another sweep though as your build settings might be slightly different than mine so I could be missing them.

**Comment by adamkaplan** [comment]
@jsom Nice. I just whipped up pretty much the exact same diff that I was going to submit as a PR. Should have checked for very recent changes!

I think I can fix the CFURL escape deprecation. I’ll pull your update and send that.

**Comment by adamkaplan** [comment]
I think you fixed them all. Thanks!
